services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    networks:
      - mern-network

  frontend:
    build:
      context: ./client
    ports:
      - "5173:4173"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
